### ISSUE TITLE
某会话已经在配置中写入了高权限，超级用户再使用 chmod 降低权限没有连带修改机制

### ISSUE THREAD

**Issue by Jerry-FaGe** [Jigsaw111/nonebot_plugin_manager#15]
举个栗子，a 插件初始权限是 757 ，某群 123456789 开关了一下这个插件，那么配置文件中会存入如下配置

```yml
a:
  group:
    123456789: 7
  mode: '757'
  status: true
  user: {}
```

这时超级用户使用 `npm chmod 755 a` 修改了全部群的 a 插件权限为 5 ，但是这时群 123456789 的权限并没有连带一起修改，配置如下

```yml
a:
  group:
    123456789: 7
  mode: '755'
  status: true
  user: {}
```

这样在超级用户修改权限之前修改过权限的会话在超级用户修改权限之后就不受全局权限限制了。
