### ISSUE TITLE
禁用所有插件之后无法启用

### ISSUE THREAD

**Issue by Bearlele** [Jigsaw111/nonebot_plugin_manager#7]
"npm unblock -a"
ATRI | 04-18 17:56:46 | INFO nonebot >> Event will be handled by <Matcher from nonebot_plugin_manager, type=message, priority=1, temp=False>
ATRI | 04-18 17:56:46 | INFO nonebot >> Matcher <Matcher from nonebot_plugin_manager, type=message, priority=1, temp=False> running is cancelled

他是把自己也给禁用掉了吗QWQ

**Comment by j1g5awi** [comment]
怪了，我记得这个 bug 已经修复了啊，看看插件版本和 plugin_list.yml（记得脱敏）

**Comment by Bearlele** [comment]
我是用pip直接安装的
nonebot-plugin-manager     0.5.9

plugin_list.yml里全都是
xxxx:
  group:
    12345678: 5
  mode: '755'
  status: true
  user: {}

**Comment by j1g5awi** [comment]
你别把插件名字也脱敏了啊，至少把 nonebot_plugin_manager 那一部分发出来

**Comment by Bearlele** [comment]
因为没有这一部分鸭 只有我自己的插件
我是直接使用npm block -a禁用了全部插件

**Comment by j1g5awi** [comment]
nonebot_plugin_manager 的部分默认一定会生成，建议你删除现有的 plugin_list.yml 再复现一遍此 bug，然后再发一下该文件

**Comment by Bearlele** [comment]
重新生成了 麻烦您看看文件路径是/root/nonebot/data/manager没错的吧

```yaml
MCSkin:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
abstract:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
admin:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
antiflash:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
chat:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
code:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
covid19:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
cp:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
ddcheck:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
draw_card:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
emojimix:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
epicfree:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
fr24:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
help:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
logo:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
mcstatus:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
memes:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
minesweeper:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
morning:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
nonebot_plugin_apscheduler:
  group: {}
  mode: '311'
  status: false
  user: {}
other:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
petpet:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
russian:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
shindan:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
simplemusic:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
status:
  group: {}
  mode: '311'
  status: false
  user: {}
what2eat:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
word_bank2:
  group:
    12345678: 4
  mode: '755'
  status: true
  user: {}
```
